name: Code Push Trigger

on:
  push:
    branches:
      - main
      - sandbox
      - quality

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, ${{ github.ref_name }} world!.    


      # Runs a single command using the runners shell
      - name: Run a second-line script
        run: echo this ${{ secrets.SECRET1 }}    
        

      # Runs a single command using the runners shell
      - name: Run a third-line script
        run: echo this ${{ vars.VAR1 }}    
