name: Code Push Trigger

on:
  push:
    branches:
      - main
      - sandbox
      - quality

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, ${{ github.ref_name }} world!.    


      # Runs a single command using the runners shell
      - name: Run a second-line script
        run: echo this ${{ secrets.SECRET1 }}    
        

      # Runs a single command using the runners shell
      - name: Run a third-line script
        run: echo this ${{ vars.VAR1 }}  
        
      - name : RUN mavan command showcase
        run: echo mvn clean deploy -DmuleDeploy -DconnectedAppClientId=${{ secrets.SECRET1 }}  -DconnectedAppClientSecret=${{ secrets.SECRET1 }}  -Denvironment=${{ vars.VAR1 }} -Dworkers=1 -DworkerType=MICRO -Dmule.env=${{ vars.VAR1 }} -Danypoint.platform.client_id=${{ secrets.SECRET1 }}  -Danypoint.platform.client_secret=${{ secrets.SECRET1 }} -DapplicationName=sb-iewc-pim-sapi -Dregion=us-east-2 -s .github/settings.xml
